### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate to use v0.14 Output Plugin API.
This PR contains major update change.
Could you bump up minor version if releasing new version of gem?
And please refer http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12 before release new version.

Thanks in advance,

### CODE REVIEW

**Comment by muddydixon** [comment]
thanks a lot! merged!

**Comment by cosmo0920** [comment]
Thank you! :smile:

**Comment by Globegitter** [comment]
@muddydixon could you release this as a new version? Would be much appreciated.

**Comment by muddydixon** [comment]
@Globegitter released!

https://rubygems.org/gems/fluent-plugin-filter

**Comment by cosmo0920** [comment]
@muddydixon I've noticed that this plugin shouldn't bump patch version.
Could you yank 0.0.6 and release 0.1.0?
`bundle update` might cause compatibility problem.

**Comment by muddydixon** [comment]
@cosmo0920 Thank you for your p-r and advice.
I yanked 0.0.6 and push 0.1.0 minor version up.

please check it. 

w/ @Globegitter

**Pull request merged**
